import type { MeldConfig } from "./config/types.js";

export function generateReadme(config: MeldConfig): string {
  const agentLabels: Record<string, string> = {
    "claude-code": "Claude Code",
    "codex-cli": "Codex CLI",
    "gemini-cli": "Gemini CLI",
  };

  const agentCommands: Record<string, string> = {
    "claude-code": "`meld claude`",
    "codex-cli": "`meld codex`",
    "gemini-cli": "`meld gemini`",
  };

  const enabledAgents = Object.entries(config.agents)
    .filter(([, a]) => a.enabled)
    .map(([name]) => name);

  const enabled = enabledAgents
    .map((a) => agentLabels[a] ?? a)
    .join(", ");

  const launchCmds = enabledAgents
    .map((a) => agentCommands[a] ?? `\`meld ${a}\``)
    .join(" / ");

  return [
    `# ${config.ide.workspaceName}`,
    "",
    `A multi-project workspace powered by [meld](https://github.com/ViktorPontinen/meld-cli).`,
    "",
    `**Enabled agents:** ${enabled}`,
    "",
    "## Getting Started",
    "",
    "1. Add projects: `meld project add`",
    "2. Add agent instructions in `context/` (markdown files)",
    "3. Generate configs: `meld gen`",
    `4. Launch an agent: ${launchCmds}`,
    "",
    "## Structure",
    "",
    "| Path | Purpose |",
    "|------|---------|",
    "| `meld.jsonc` | Central configuration |",
    "| `context/` | Markdown instructions for agents |",
    "| `commands/` | Slash commands |",
    "| `skills/` | Reusable agent skills |",
    "| `artifacts/` | Research, plans, and notes |",
    "| `scratch/` | Temporary work (gitignored) |",
    "| `agents/` | Generated output (gitignored) |",
    "",
    "## Context",
    "",
    "Files in the root of `context/` are inlined into agent instructions.",
    "Subfolders are copied into each agent's working directory, so you can",
    "link to them with relative paths like `./subfolder/doc.md`.",
    "",
    "```",
    "context/",
    "  01-role.md          # Inlined into CLAUDE.md / AGENTS.md / GEMINI.md",
    "  02-guardrails.md    # Inlined (alphabetical order)",
    "  reference/          # Copied as agents/<name>/reference/",
    "    api.md",
    "    patterns.md",
    "```",
    "",
    "The filename determines order — use numeric prefixes to control sequencing.",
    "After editing, run `meld gen` to regenerate agent configs.",
    "",
    "## MCP Servers",
    "",
    "MCP servers are defined once in `meld.jsonc` under the `mcp` key and automatically",
    "translated into each agent's native config format (`.mcp.json`, `.codex/config.toml`,",
    "`.gemini/settings.json`).",
    "",
    "### Stdio server (local process)",
    "",
    "Runs a command as a child process, communicating over stdin/stdout.",
    "",
    "```jsonc",
    '"my-server": {',
    '  "command": "npx",',
    '  "args": ["-y", "my-mcp-server@latest"],',
    '  "env": {               // optional',
    '    "API_KEY": "sk-..."',
    "  }",
    "}",
    "```",
    "",
    "### HTTP server (remote)",
    "",
    "Connects to a remote MCP endpoint over HTTP.",
    "",
    "```jsonc",
    '"my-server": {',
    '  "type": "http",',
    '  "url": "https://mcp.example.com/mcp",',
    '  "headers": {            // optional',
    '    "Authorization": "Bearer tok-..."',
    "  }",
    "}",
    "```",
    "",
    "### Scoping servers to specific agents",
    "",
    "By default every MCP server is available to all enabled agents.",
    "Use `agents` to restrict a server to specific agents:",
    "",
    "```jsonc",
    '"my-server": {',
    '  "command": "node",',
    '  "args": ["server.js"],',
    '  "agents": ["claude-code"]  // only generated for Claude Code',
    "}",
    "```",
    "",
    "Valid agent names: `claude-code`, `codex-cli`, `gemini-cli`.",
    "",
    "## Commands",
    "",
    "| Command | Description |",
    "|---------|-------------|",
    "| `meld gen` | Generate agent configs from `meld.jsonc` |",
    "| `meld gen --dry-run` | Preview without writing files |",
    "| `meld project add` | Register a project |",
    "| `meld project list` | List registered projects |",
    "| `meld open` | Open workspace in IDE |",
    "| `meld update` | Re-scaffold hub structure |",
    "",
    "> Edit `meld.jsonc` for configuration. Run `meld gen` after changes.",
    "",
  ].join("\n");
}
